force-app/main/default/objects/Limits__c/Limits__c.object-meta.xml
<CustomObject>
    <label>Limits</label>
    <nameField>
        <label>Limits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limits__c/fields/Next_Snapshot_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Snapshot_Date__c</fullName>
    <formula>Latest_Snapshot__c +  (Scheduled_Period__c / 24)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Snapshot Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LimitsScheduler.cls
public class LimitsScheduler implements Database.Batchable<SObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext bc){
        DateTime myTime = System.now().addMinutes(2);
        String query = 'SELECT Id,Name,ExternalId__c FROM LIMITS__c WHERE Next_Snapshot_Date__c < :myTime OR Next_Snapshot_Date__c = NULL';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Limits__c> scope){
        LimitsUtil.createSnapShot(scope);
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
    
    public void execute(System.SchedulableContext sc){
        Database.executeBatch(new LimitsScheduler());
    }
}