force-app/main/default/objects/Limit_Snapshot__c/Limit_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Limit Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Snapshot</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Snapshot__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <label>Limits</label>
    <referenceTo>Limits__c</referenceTo>
    <relationshipLabel>Limit Snapshot</relationshipLabel>
    <relationshipName>Limit_Snapshot</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__c/fields/Mark_for_Delete__c.field-meta.xml
<CustomField>
    <fullName>Mark_for_Delete__c</fullName>
    <formula>IF( NOW() &gt; (CreatedDate + Limits__r.Retention_Days__c  ), True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mark for Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Limits__c/Limits__c.object-meta.xml
<CustomObject>
    <label>Limits</label>
    <nameField>
        <label>Limits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LimitsDeleteScheduler.cls
public class LimitsDeleteScheduler implements Database.Batchable<SObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext bc){
        DateTime myTime = System.now().addMinutes(2);
        String query = 'SELECT Id from Limit_SnapShot__c WHERE Mark_for_Delete__c = True';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Limits__c> scope){
        delete scope;
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
    
    public void execute(System.SchedulableContext sc){
        Database.executeBatch(new LimitsDeleteScheduler());
    }
}